import '@servicenow/sdk/global'
import { Record } from '@servicenow/sdk/core'
import { demoIngredientsManufacturer, demoOperationsManufacturer, demoPackagingManufacturer, demoSanitationManufacturer } from './demo-manufacturers.now'
import { beverageServiceModelCategory, cleaningModelCategory, ingredientsModelCategory, operationsModelCategory, packagingModelCategory, safetyModelCategory } from './model-categories.now'

const demo = { installMethod: 'demo' as const }

export const demoPaperModel = Record({ $id: Now.ID['demo_store_paper_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Thermal Receipt Paper Roll', model_number: 'DEMO-COFFEE-OPS-001', manufacturer: demoOperationsManufacturer, cmdb_model_category: [operationsModelCategory], store_category: 'operations', unit_of_measure: 'roll', active_for_ordering: true, demo_data: true } as any })
export const demoBagModel = Record({ $id: Now.ID['demo_store_bag_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Paper Carryout Bag', model_number: 'DEMO-COFFEE-PKG-001', manufacturer: demoPackagingManufacturer, cmdb_model_category: [packagingModelCategory], store_category: 'packaging', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoGloveModel = Record({ $id: Now.ID['demo_store_glove_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Food-Safe Nitrile Gloves', model_number: 'DEMO-COFFEE-SAFE-001', manufacturer: demoSanitationManufacturer, cmdb_model_category: [safetyModelCategory], store_category: 'safety', unit_of_measure: 'box', active_for_ordering: true, demo_data: true } as any })
export const demoHotCup12 = Record({ $id: Now.ID['demo_hot_cup_12_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO 12 oz Hot Cup', model_number: 'DEMO-COFFEE-PKG-012', manufacturer: demoPackagingManufacturer, cmdb_model_category: [packagingModelCategory], store_category: 'packaging', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoHotCup16 = Record({ $id: Now.ID['demo_hot_cup_16_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO 16 oz Hot Cup', model_number: 'DEMO-COFFEE-PKG-016', manufacturer: demoPackagingManufacturer, cmdb_model_category: [packagingModelCategory], store_category: 'packaging', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoHotCup20 = Record({ $id: Now.ID['demo_hot_cup_20_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO 20 oz Hot Cup', model_number: 'DEMO-COFFEE-PKG-020', manufacturer: demoPackagingManufacturer, cmdb_model_category: [packagingModelCategory], store_category: 'packaging', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoColdCup16 = Record({ $id: Now.ID['demo_cold_cup_16_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO 16 oz Cold Cup', model_number: 'DEMO-COFFEE-PKG-C16', manufacturer: demoPackagingManufacturer, cmdb_model_category: [packagingModelCategory], store_category: 'packaging', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoColdCup24 = Record({ $id: Now.ID['demo_cold_cup_24_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO 24 oz Cold Cup', model_number: 'DEMO-COFFEE-PKG-C24', manufacturer: demoPackagingManufacturer, cmdb_model_category: [packagingModelCategory], store_category: 'packaging', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoHotLid = Record({ $id: Now.ID['demo_hot_lid_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Universal Hot Cup Lid', model_number: 'DEMO-COFFEE-PKG-HLID', manufacturer: demoPackagingManufacturer, cmdb_model_category: [packagingModelCategory], store_category: 'packaging', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoColdLid = Record({ $id: Now.ID['demo_cold_lid_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Flat Cold Cup Lid', model_number: 'DEMO-COFFEE-PKG-CLID', manufacturer: demoPackagingManufacturer, cmdb_model_category: [packagingModelCategory], store_category: 'packaging', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoSleeve = Record({ $id: Now.ID['demo_sleeve_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Corrugated Cup Sleeve', model_number: 'DEMO-COFFEE-PKG-SLV', manufacturer: demoPackagingManufacturer, cmdb_model_category: [packagingModelCategory], store_category: 'packaging', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoCarrier = Record({ $id: Now.ID['demo_carrier_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Four-Cup Beverage Carrier', model_number: 'DEMO-COFFEE-PKG-CAR', manufacturer: demoPackagingManufacturer, cmdb_model_category: [packagingModelCategory], store_category: 'packaging', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoNapkin = Record({ $id: Now.ID['demo_napkin_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Beverage Napkin', model_number: 'DEMO-COFFEE-PKG-NAP', manufacturer: demoPackagingManufacturer, cmdb_model_category: [packagingModelCategory], store_category: 'packaging', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoStraw = Record({ $id: Now.ID['demo_straw_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Compostable Cold Drink Straw', model_number: 'DEMO-COFFEE-PKG-STR', manufacturer: demoPackagingManufacturer, cmdb_model_category: [packagingModelCategory], store_category: 'packaging', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoEspresso = Record({ $id: Now.ID['demo_espresso_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Espresso Roast Whole Bean', model_number: 'DEMO-COFFEE-ING-ESP', manufacturer: demoIngredientsManufacturer, cmdb_model_category: [ingredientsModelCategory], store_category: 'ingredients', unit_of_measure: '5 lb bag', active_for_ordering: true, demo_data: true } as any })
export const demoDecaf = Record({ $id: Now.ID['demo_decaf_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Decaf Espresso Whole Bean', model_number: 'DEMO-COFFEE-ING-DCF', manufacturer: demoIngredientsManufacturer, cmdb_model_category: [ingredientsModelCategory], store_category: 'ingredients', unit_of_measure: '5 lb bag', active_for_ordering: true, demo_data: true } as any })
export const demoVanilla = Record({ $id: Now.ID['demo_vanilla_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Vanilla Beverage Syrup', model_number: 'DEMO-COFFEE-ING-VAN', manufacturer: demoIngredientsManufacturer, cmdb_model_category: [ingredientsModelCategory], store_category: 'ingredients', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoCaramel = Record({ $id: Now.ID['demo_caramel_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Caramel Beverage Sauce', model_number: 'DEMO-COFFEE-ING-CAR', manufacturer: demoIngredientsManufacturer, cmdb_model_category: [ingredientsModelCategory], store_category: 'ingredients', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoOat = Record({ $id: Now.ID['demo_oat_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Barista Oat Beverage', model_number: 'DEMO-COFFEE-ING-OAT', manufacturer: demoIngredientsManufacturer, cmdb_model_category: [ingredientsModelCategory], store_category: 'ingredients', unit_of_measure: '12-carton case', active_for_ordering: true, demo_data: true } as any })
export const demoLabel = Record({ $id: Now.ID['demo_label_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Mobile Order Label Roll', model_number: 'DEMO-COFFEE-OPS-LBL', manufacturer: demoOperationsManufacturer, cmdb_model_category: [operationsModelCategory], store_category: 'operations', unit_of_measure: 'roll', active_for_ordering: true, demo_data: true } as any })
export const demoSanitizer = Record({ $id: Now.ID['demo_sanitizer_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Foodservice Sanitizer Concentrate', model_number: 'DEMO-COFFEE-CLN-SAN', manufacturer: demoSanitationManufacturer, cmdb_model_category: [cleaningModelCategory], store_category: 'cleaning', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
export const demoCleaningTablet = Record({ $id: Now.ID['demo_cleaning_tablet_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Espresso Machine Cleaning Tablets', model_number: 'DEMO-COFFEE-CLN-TAB', manufacturer: demoSanitationManufacturer, cmdb_model_category: [cleaningModelCategory], store_category: 'cleaning', unit_of_measure: 'bottle', active_for_ordering: true, demo_data: true } as any })
export const demoTowel = Record({ $id: Now.ID['demo_towel_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Reusable Bar Towel Pack', model_number: 'DEMO-COFFEE-CLN-TWL', manufacturer: demoSanitationManufacturer, cmdb_model_category: [cleaningModelCategory], store_category: 'cleaning', unit_of_measure: 'pack', active_for_ordering: true, demo_data: true } as any })
export const demoFilter = Record({ $id: Now.ID['demo_filter_model'], table: 'x_sln_store_suppli_store_supply_model', $meta: demo, data: { name: 'DEMO Commercial Coffee Filter', model_number: 'DEMO-COFFEE-BEV-FLT', manufacturer: demoIngredientsManufacturer, cmdb_model_category: [beverageServiceModelCategory], store_category: 'beverage_service', unit_of_measure: 'case', active_for_ordering: true, demo_data: true } as any })
