import '@servicenow/sdk/global'
import { Record } from '@servicenow/sdk/core'
import { demoStockroom101, demoStockroom205, demoStockroom310, demoStockroom415, demoStockroom520, demoStockroom625 } from './demo.now'
import { demoBagModel, demoColdCup24, demoEspresso, demoGloveModel, demoHotCup12, demoHotCup16, demoHotLid, demoLabel, demoOat, demoPaperModel, demoSanitizer } from './demo-models.now'
import { cleaningModelCategory, ingredientsModelCategory, operationsModelCategory, packagingModelCategory, safetyModelCategory } from './model-categories.now'

const demo = { installMethod: 'demo' as const }

Record({ $id: Now.ID['demo_inventory_paper_101'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Midtown - Receipt Paper', model: demoPaperModel, model_category: operationsModelCategory, stockroom: demoStockroom101, quantity: 24, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_bag_101'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Midtown - Carryout Bags', model: demoBagModel, model_category: packagingModelCategory, stockroom: demoStockroom101, quantity: 40, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_gloves_205'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Lakeside - Nitrile Gloves', model: demoGloveModel, model_category: safetyModelCategory, stockroom: demoStockroom205, quantity: 8, install_status: 6, substatus: 'available' } })

Record({ $id: Now.ID['demo_inventory_hot12_101'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Midtown - 12 oz Hot Cups', model: demoHotCup12, model_category: packagingModelCategory, stockroom: demoStockroom101, quantity: 18, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_hot16_101'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Midtown - 16 oz Hot Cups', model: demoHotCup16, model_category: packagingModelCategory, stockroom: demoStockroom101, quantity: 4, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_cold24_101'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Midtown - 24 oz Cold Cups', model: demoColdCup24, model_category: packagingModelCategory, stockroom: demoStockroom101, quantity: 0, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_hotlid_101'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Midtown - Hot Cup Lids', model: demoHotLid, model_category: packagingModelCategory, stockroom: demoStockroom101, quantity: 22, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_espresso_101'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Midtown - Espresso Roast', model: demoEspresso, model_category: ingredientsModelCategory, stockroom: demoStockroom101, quantity: 3, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_oat_101'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Midtown - Oat Beverage', model: demoOat, model_category: ingredientsModelCategory, stockroom: demoStockroom101, quantity: 2, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_label_101'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Midtown - Mobile Labels', model: demoLabel, model_category: operationsModelCategory, stockroom: demoStockroom101, quantity: 1, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_sanitizer_101'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Midtown - Sanitizer', model: demoSanitizer, model_category: cleaningModelCategory, stockroom: demoStockroom101, quantity: 6, install_status: 6, substatus: 'available' } })

Record({ $id: Now.ID['demo_inventory_hot12_205'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Lakeside - 12 oz Hot Cups', model: demoHotCup12, model_category: packagingModelCategory, stockroom: demoStockroom205, quantity: 30, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_hot16_205'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Lakeside - 16 oz Hot Cups', model: demoHotCup16, model_category: packagingModelCategory, stockroom: demoStockroom205, quantity: 24, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_cold24_205'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Lakeside - 24 oz Cold Cups', model: demoColdCup24, model_category: packagingModelCategory, stockroom: demoStockroom205, quantity: 14, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_hotlid_205'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Lakeside - Hot Cup Lids', model: demoHotLid, model_category: packagingModelCategory, stockroom: demoStockroom205, quantity: 28, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_espresso_205'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Lakeside - Espresso Roast', model: demoEspresso, model_category: ingredientsModelCategory, stockroom: demoStockroom205, quantity: 8, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_oat_205'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Lakeside - Oat Beverage', model: demoOat, model_category: ingredientsModelCategory, stockroom: demoStockroom205, quantity: 10, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_label_205'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Lakeside - Mobile Labels', model: demoLabel, model_category: operationsModelCategory, stockroom: demoStockroom205, quantity: 3, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_sanitizer_205'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Lakeside - Sanitizer', model: demoSanitizer, model_category: cleaningModelCategory, stockroom: demoStockroom205, quantity: 4, install_status: 6, substatus: 'available' } })

Record({ $id: Now.ID['demo_inventory_hot12_310'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Brooklyn - 12 oz Hot Cups', model: demoHotCup12, model_category: packagingModelCategory, stockroom: demoStockroom310, quantity: 12, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_hot16_310'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Brooklyn - 16 oz Hot Cups', model: demoHotCup16, model_category: packagingModelCategory, stockroom: demoStockroom310, quantity: 8, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_cold24_310'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Brooklyn - 24 oz Cold Cups', model: demoColdCup24, model_category: packagingModelCategory, stockroom: demoStockroom310, quantity: 22, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_hotlid_310'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Brooklyn - Hot Cup Lids', model: demoHotLid, model_category: packagingModelCategory, stockroom: demoStockroom310, quantity: 10, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_espresso_310'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Brooklyn - Espresso Roast', model: demoEspresso, model_category: ingredientsModelCategory, stockroom: demoStockroom310, quantity: 4, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_oat_310'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Brooklyn - Oat Beverage', model: demoOat, model_category: ingredientsModelCategory, stockroom: demoStockroom310, quantity: 1, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_label_310'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Brooklyn - Mobile Labels', model: demoLabel, model_category: operationsModelCategory, stockroom: demoStockroom310, quantity: 12, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_sanitizer_310'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Brooklyn - Sanitizer', model: demoSanitizer, model_category: cleaningModelCategory, stockroom: demoStockroom310, quantity: 3, install_status: 6, substatus: 'available' } })

Record({ $id: Now.ID['demo_inventory_hot12_415'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Pike - 12 oz Hot Cups', model: demoHotCup12, model_category: packagingModelCategory, stockroom: demoStockroom415, quantity: 20, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_hot16_415'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Pike - 16 oz Hot Cups', model: demoHotCup16, model_category: packagingModelCategory, stockroom: demoStockroom415, quantity: 18, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_cold24_415'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Pike - 24 oz Cold Cups', model: demoColdCup24, model_category: packagingModelCategory, stockroom: demoStockroom415, quantity: 10, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_hotlid_415'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Pike - Hot Cup Lids', model: demoHotLid, model_category: packagingModelCategory, stockroom: demoStockroom415, quantity: 25, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_espresso_415'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Pike - Espresso Roast', model: demoEspresso, model_category: ingredientsModelCategory, stockroom: demoStockroom415, quantity: 2, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_oat_415'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Pike - Oat Beverage', model: demoOat, model_category: ingredientsModelCategory, stockroom: demoStockroom415, quantity: 5, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_label_415'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Pike - Mobile Labels', model: demoLabel, model_category: operationsModelCategory, stockroom: demoStockroom415, quantity: 8, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_sanitizer_415'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Pike - Sanitizer', model: demoSanitizer, model_category: cleaningModelCategory, stockroom: demoStockroom415, quantity: 7, install_status: 6, substatus: 'available' } })

Record({ $id: Now.ID['demo_inventory_hot12_520'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Airport - 12 oz Hot Cups', model: demoHotCup12, model_category: packagingModelCategory, stockroom: demoStockroom520, quantity: 5, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_hot16_520'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Airport - 16 oz Hot Cups', model: demoHotCup16, model_category: packagingModelCategory, stockroom: demoStockroom520, quantity: 0, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_cold24_520'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Airport - 24 oz Cold Cups', model: demoColdCup24, model_category: packagingModelCategory, stockroom: demoStockroom520, quantity: 3, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_hotlid_520'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Airport - Hot Cup Lids', model: demoHotLid, model_category: packagingModelCategory, stockroom: demoStockroom520, quantity: 6, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_espresso_520'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Airport - Espresso Roast', model: demoEspresso, model_category: ingredientsModelCategory, stockroom: demoStockroom520, quantity: 1, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_oat_520'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Airport - Oat Beverage', model: demoOat, model_category: ingredientsModelCategory, stockroom: demoStockroom520, quantity: 0, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_label_520'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Airport - Mobile Labels', model: demoLabel, model_category: operationsModelCategory, stockroom: demoStockroom520, quantity: 2, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_sanitizer_520'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Airport - Sanitizer', model: demoSanitizer, model_category: cleaningModelCategory, stockroom: demoStockroom520, quantity: 2, install_status: 6, substatus: 'available' } })

Record({ $id: Now.ID['demo_inventory_hot12_625'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Suburban - 12 oz Hot Cups', model: demoHotCup12, model_category: packagingModelCategory, stockroom: demoStockroom625, quantity: 45, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_hot16_625'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Suburban - 16 oz Hot Cups', model: demoHotCup16, model_category: packagingModelCategory, stockroom: demoStockroom625, quantity: 36, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_cold24_625'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Suburban - 24 oz Cold Cups', model: demoColdCup24, model_category: packagingModelCategory, stockroom: demoStockroom625, quantity: 28, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_hotlid_625'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Suburban - Hot Cup Lids', model: demoHotLid, model_category: packagingModelCategory, stockroom: demoStockroom625, quantity: 40, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_espresso_625'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Suburban - Espresso Roast', model: demoEspresso, model_category: ingredientsModelCategory, stockroom: demoStockroom625, quantity: 10, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_oat_625'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Suburban - Oat Beverage', model: demoOat, model_category: ingredientsModelCategory, stockroom: demoStockroom625, quantity: 14, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_label_625'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Suburban - Mobile Labels', model: demoLabel, model_category: operationsModelCategory, stockroom: demoStockroom625, quantity: 6, install_status: 6, substatus: 'available' } })
Record({ $id: Now.ID['demo_inventory_sanitizer_625'], table: 'alm_consumable', $meta: demo, data: { display_name: 'DEMO Suburban - Sanitizer', model: demoSanitizer, model_category: cleaningModelCategory, stockroom: demoStockroom625, quantity: 9, install_status: 6, substatus: 'available' } })
